main:
  project_name: nyc_airbnb
  experiment_name: development
  steps: all

etl:
  sample: "sample1.csv"
  input_artifact: "sample.csv:latest"
  output_artifact: "clean_sample.csv"
  output_type: "cleaned_data"
  output_description: "Data with outliers and nulls removed"
  min_price: 10
  max_price: 350

data_check:
  kl_threshold: 0.2

modeling:
  test_size: 0.2
  val_size: 0.2
  random_seed: 42
  stratify_by: "neighbourhood_group"
  max_tfidf_features: 50
  random_forest:
    n_estimators: 100
    max_depth: 10
    min_samples_split: 2
    min_samples_leaf: 1
    n_jobs: -1
    criterion: squared_error
    max_features: 0.5
    oob_score: true