name: test_regression_model
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.0
  - pip=23.3.1
  - pandas=2.1.3
  - scikit-learn=1.5.2
  - numpy=1.26.2
  - pyyaml=6.0.1
  - requests=2.31.0
  - pip:
      - mlflow==2.18.0
      - wandb==0.16.0
      - protobuf==4.25.1
      - git+https://github.com/udacity/Project-Build-an-ML-Pipeline-Starter.git#egg=wandb-utils&subdirectory=components
      - scipy==1.11.4
      - joblib==1.3.2