trainval_artifact: train_data.csv:latest
val_size: 0.2
random_seed: 42
stratify_by: neighbourhood_group
max_tfidf_features: 50

output_artifact: random_forest_model
output_type: model

modeling:
  random_forest:
    max_depth: 10
    n_estimators: 100
    min_samples_split: 2
    min_samples_leaf: 1
    random_state: 42