name: train_random_forest
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.0
  - hydra-core=1.3.2
  - matplotlib=3.8.2
  - pandas=2.1.3
  - pip=23.3.1
  - scikit-learn=1.5.2
  - numpy=1.26.2        # Explicitly include numpy to avoid potential conflicts
  - pip:
      - mlflow==2.8.1
      - wandb==0.16.0